languageCode = "en-us"
title = "DCRDEX | Cryptocurrency Exchange"
baseurl = "https://dex.decred.org/"

[params]
  # Site image and description used to populate og tags.
  images = ["/og-card.png"]
  description = "DCRDEX is an open source, peer-to-peer cryptocurrency exchange built by the Decred Project."

  # Bison Wallet URLs
  win_bisonw_installer_url      = "https://github.com/decred/dcrdex/releases/download/v1.0.4/bisonw-desktop-windows-amd64-v1.0.4.msi"
  win_bisonw_binary_url         = "https://github.com/decred/dcrdex/releases/download/v1.0.4/bisonw-windows-amd64-v1.0.4.zip"
  mac_bisonw_installer_amd_url  = "https://github.com/decred/dcrdex/releases/download/v1.0.4/bisonw-desktop-darwin-amd64-v1.0.4.dmg"
  mac_bisonw_binary_amd_url     = "https://github.com/decred/dcrdex/releases/download/v1.0.4/bisonw-darwin-amd64-v1.0.4.tar.gz"
  mac_bisonw_installer_arm_url  = "https://github.com/decred/dcrdex/releases/download/v1.0.4/bisonw-desktop-darwin-arm64-v1.0.4.dmg"
  mac_bisonw_binary_arm_url     = "https://github.com/decred/dcrdex/releases/download/v1.0.4/bisonw-darwin-arm64-v1.0.4.tar.gz"
  lin_bisonw_binary_url         = "https://github.com/decred/dcrdex/releases/download/v1.0.4/bisonw-linux-amd64-v1.0.4.tar.gz"
  lin_bisonw_deb_url            = "https://github.com/decred/dcrdex/releases/download/v1.0.4/bisonw-desktop-linux-amd64-v1.0.4.deb"
  lin_bisonw_arm_url            = "https://github.com/decred/dcrdex/releases/download/v1.0.4/bisonw-linux-arm64-v1.0.4.tar.gz"

  # Decrediton URLs
  win_decrediton_url = "https://github.com/decred/decred-binaries/releases/download/v2.0.6/decrediton-windows-amd64-v2.0.6.exe"
  mac_decrediton_url = "https://github.com/decred/decred-binaries/releases/download/v2.0.6/decrediton-darwin-amd64-v2.0.6.dmg"
  m1_decrediton_url  = "https://github.com/decred/decred-binaries/releases/download/v2.0.6/decrediton-darwin-arm64-v2.0.6.dmg"
  lin_decrediton_url = "https://github.com/decred/decred-binaries/releases/download/v2.0.6/decrediton-linux-amd64-v2.0.6.AppImage"
  tar_decrediton_url = "https://github.com/decred/decred-binaries/releases/download/v2.0.6/decrediton-linux-amd64-v2.0.6.tar.gz"
  dexreleases_url    = "https://github.com/decred/dcrdex/releases/tag/v1.0.4"
  umbrel_community_app_store_url = "https://github.com/decred/umbrel-app-store"
